In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [3]:
print(type(a))

<class 'numpy.ndarray'>


In [4]:
a.shape

(4,)

In [5]:
b=np.array([[1,2,3,4],[5,6,7,8]])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [6]:
print(b.shape)

(2, 4)


In [7]:
b.T

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [9]:
np.dot(b,b.T)

array([[ 30,  70],
       [ 70, 174]])

In [10]:
np.random.randint(60,100,10)

array([79, 96, 66, 84, 76, 93, 64, 95, 91, 91])

In [15]:
np.random.randint(60,100,(5,5))

array([[85, 98, 67, 99, 87],
       [81, 80, 76, 75, 76],
       [99, 88, 67, 96, 84],
       [87, 97, 79, 68, 98],
       [72, 88, 81, 99, 91]])

In [16]:
matrix=np.random.randint(60,100,(5,5))
print(matrix)

[[66 64 94 89 82]
 [94 67 92 84 60]
 [70 84 77 90 68]
 [96 62 95 88 70]
 [82 88 69 73 61]]


In [17]:
np.max(matrix)

96

In [18]:
np.min(matrix)

60

In [25]:
a=np.array([0,1,10,10,2,-8,6,6,6,6,8,10])
np.argmin(a)
#argmin returns the min index

5

In [26]:
np.argmax(a)

2

In [27]:
print(np.unique(a))

[-8  0  1  2  6  8 10]


In [28]:
b=np.unique(a,return_counts=True)
print(b)

(array([-8,  0,  1,  2,  6,  8, 10]), array([1, 1, 1, 1, 4, 1, 3]))


In [29]:
print(b[0])

[-8  0  1  2  6  8 10]


In [30]:
print(b[1])

[1 1 1 1 4 1 3]


In [31]:
#program to find out number with the highest frequency in the array
b=np.unique(a,return_counts=True)
print(b)


(array([-8,  0,  1,  2,  6,  8, 10]), array([1, 1, 1, 1, 4, 1, 3]))


In [32]:
idx=np.argmax(b[1])
element=b[0][idx]
print(element)

6


In [33]:
matrix

array([[66, 64, 94, 89, 82],
       [94, 67, 92, 84, 60],
       [70, 84, 77, 90, 68],
       [96, 62, 95, 88, 70],
       [82, 88, 69, 73, 61]])

In [34]:
 matrix[2:4,1:4]   #slicing of arrays

array([[84, 77, 90],
       [62, 95, 88]])

In [35]:
matrix[0][0]

66

In [6]:
import numpy as np

In [7]:
#Data Visualisation

In [8]:
import matplotlib.pyplot as plt

In [9]:
x=np.array([1,2,3,4,5])
y=x**2+3
print(y)

[ 4  7 12 19 28]


In [10]:
print(x,y)

[1 2 3 4 5] [ 4  7 12 19 28]


In [2]:
import numpy as np

In [3]:
a =np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [4]:
print(type(a))

<class 'numpy.ndarray'>


In [9]:
a[2]

3

In [5]:
print(a.shape)

(5,)


In [46]:
b=np.array([[1],[2],[3],[4],[5]])
print(b)
print(b.shape)

[[1]
 [2]
 [3]
 [4]
 [5]]
(5, 1)


In [8]:
b[0][0]

1

In [38]:
c=np.array([[1,2,3],[4,5,6]])
print(c.shape)
print(c)

(2, 3)
[[1 2 3]
 [4 5 6]]


In [11]:
print(c[1][1])

5


In [13]:
a=np.zeros((3,3))
print(a)
print(type(a))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
<class 'numpy.ndarray'>


In [4]:
import numpy as np
b=np.ones((2,5))
print(b)
print(type(b))

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
<class 'numpy.ndarray'>


In [16]:
#Array of some consatants
c=np.full((3,2),5)
print(c)

[[5 5]
 [5 5]
 [5 5]]


In [18]:
#Identity matrix -size/square matrix
d=np.eye(5)
print(d)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [19]:
#Random Matrix
randomMatrix= np.random.random((2,3))
print(randomMatrix)

[[0.64547991 0.84757211 0.88399114]
 [0.13194272 0.76894298 0.04285625]]


In [20]:
print(randomMatrix[ : ,1])

[0.84757211 0.76894298]


In [21]:
print(randomMatrix[ : ,2])

[0.88399114 0.04285625]


In [48]:
randomMatrix[1,1:3] =1
print(randomMatrix)

[[0.64547991 0.84757211 0.88399114]
 [0.13194272 1.         1.        ]]


In [40]:
#updation of rows and columns
z=np.zeros((3,3),dtype =np.int64)
print(z)
z[1,:]= 5
z[: ,-1]=7
print(z)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[0 0 7]
 [5 5 7]
 [0 0 7]]


In [41]:
#data types
print(z.dtype)

int64


In [50]:
#Mathematical opperation

x=np.array([[1,2],[3,4]])
y=np.array([[5,6],[7,8]])
print(x+y)
print(np.add(x,y))
print(x-y)
print(np.subtract(x,y))

[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[-4 -4]
 [-4 -4]]


In [51]:
print(x*y)
print(np.multiply(x,y))

[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]


In [52]:
print(x/y)
print(np.divide(x,y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [54]:
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


In [57]:
#Matrix multiplication. / dot products
print(x)
print(y)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [59]:
print(x.dot(y))
print(np.dot(x,y))

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [61]:
#multiplication (dot product)of vectors=>scalar
a=np.array([1,2,3,4])
b=np.array([1,2,3,4])
print(a.dot(b))

30


In [62]:
print(a)

[1 2 3 4]


In [63]:
print(sum(a))

10


In [69]:
print(x)
print(y)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [85]:
print(np.sum(x))
print(np.sum(y))
print(np.sum(x,axis=0))#sum of columns
print(np.sum(y,axis=0))#sum of columns
print(np.sum(x,axis=1))#sum of rows
print(np.sum(y,axis=1))#SUM OF ROWS

10
26
[4 6]
[12 14]
[3 7]
[11 15]


In [77]:
print(y)

[[5 6]
 [7 8]]


In [78]:
print(np.sum(y))

26
